---
title: "Oil Refinery Ownership Analysis"
author: "M Ilham AR Santoso"
date: "07/29/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```

```{r install-packages}
#install.packages("readxl")
library(readxl)
#install.packages("dplyr")
library(dplyr)
#install.packages("readr")
library(readr)
#install.packages("stringr")
library(stringr)
#install.packages("tidyr")
library(tidyr)
```

```{r read-file}
calls_2010 <- read_excel("~/Oil-Refinery/Data/CY10.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2010 <- read_excel("~/Oil-Refinery/Data/CY10.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2010 <- read_excel("~/Oil-Refinery/Data/CY10.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2010 <- read_excel("~/Oil-Refinery/Data/CY10.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2011 <- read_excel("~/Oil-Refinery/Data/CY11.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2011 <- read_excel("~/Oil-Refinery/Data/CY11.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2011 <- read_excel("~/Oil-Refinery/Data/CY11.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2011 <- read_excel("~/Oil-Refinery/Data/CY11.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2012 <- read_excel("~/Oil-Refinery/Data/CY12.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2012 <- read_excel("~/Oil-Refinery/Data/CY12.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2012 <- read_excel("~/Oil-Refinery/Data/CY12.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2012 <- read_excel("~/Oil-Refinery/Data/CY12.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2013 <- read_excel("~/Oil-Refinery/Data/CY13.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2013 <- read_excel("~/Oil-Refinery/Data/CY13.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2013 <- read_excel("~/Oil-Refinery/Data/CY13.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2013 <- read_excel("~/Oil-Refinery/Data/CY13.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2014 <- read_excel("~/Oil-Refinery/Data/CY14.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2014 <- read_excel("~/Oil-Refinery/Data/CY14.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2014 <- read_excel("~/Oil-Refinery/Data/CY14.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2014 <- read_excel("~/Oil-Refinery/Data/CY14.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2015 <- read_excel("~/Oil-Refinery/Data/CY15.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2015 <- read_excel("~/Oil-Refinery/Data/CY15.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2015 <- read_excel("~/Oil-Refinery/Data/CY15.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2015 <- read_excel("~/Oil-Refinery/Data/CY15.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2016 <- read_excel("~/Oil-Refinery/Data/CY16.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2016 <- read_excel("~/Oil-Refinery/Data/CY16.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2016 <- read_excel("~/Oil-Refinery/Data/CY16.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2016 <- read_excel("~/Oil-Refinery/Data/CY16.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2017 <- read_excel("~/Oil-Refinery/Data/CY17.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2017 <- read_excel("~/Oil-Refinery/Data/CY17.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2017 <- read_excel("~/Oil-Refinery/Data/CY17.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2017 <- read_excel("~/Oil-Refinery/Data/CY17.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2018 <- read_excel("~/Oil-Refinery/Data/CY18.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2018 <- read_excel("~/Oil-Refinery/Data/CY18.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2018 <- read_excel("~/Oil-Refinery/Data/CY18.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2018 <- read_excel("~/Oil-Refinery/Data/CY18.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2019 <- read_excel("~/Oil-Refinery/Data/CY19.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2019 <- read_excel("~/Oil-Refinery/Data/CY19.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2019 <- read_excel("~/Oil-Refinery/Data/CY19.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2019 <- read_excel("~/Oil-Refinery/Data/CY19.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2020 <- read_excel("~/Oil-Refinery/Data/CY20.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2020 <- read_excel("~/Oil-Refinery/Data/CY20.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2020 <- read_excel("~/Oil-Refinery/Data/CY20.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2020 <- read_excel("~/Oil-Refinery/Data/CY20.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2021 <- read_excel("~/Oil-Refinery/Data/CY21.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2021 <- read_excel("~/Oil-Refinery/Data/CY21.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2021 <- read_excel("~/Oil-Refinery/Data/CY21.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2021 <- read_excel("~/Oil-Refinery/Data/CY21.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2022 <- read_excel("~/Oil-Refinery/Data/CY22.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2022 <- read_excel("~/Oil-Refinery/Data/CY22.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2022 <- read_excel("~/Oil-Refinery/Data/CY22.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2022 <- read_excel("~/Oil-Refinery/Data/CY22.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2023 <- read_excel("~/Oil-Refinery/Data/CY23.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2023 <- read_excel("~/Oil-Refinery/Data/CY23.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2023 <- read_excel("~/Oil-Refinery/Data/CY23.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2023 <- read_excel("~/Oil-Refinery/Data/CY23.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")

calls_2024 <- read_excel("~/Oil-Refinery/Data/CY24.xlsx", sheet = "CALLS", na = "NA")
incident_commons_2024 <- read_excel("~/Oil-Refinery/Data/CY24.xlsx", sheet = "INCIDENT_COMMONS", na = "NA")
incident_details_2024 <- read_excel("~/Oil-Refinery/Data/CY24.xlsx", sheet = "INCIDENT_DETAILS", na = "NA")
material_involved_2024 <- read_excel("~/Oil-Refinery/Data/CY24.xlsx", sheet = "MATERIAL_INVOLVED", na = "NA")
```


```{r}
full_2010 <- calls_2010 %>%
  full_join(incident_commons_2010, by = "SEQNOS") %>%
  full_join(incident_details_2010, by = "SEQNOS") %>%
  full_join(material_involved_2010, by = "SEQNOS")

full_2011 <- calls_2011 %>%
  full_join(incident_commons_2011, by = "SEQNOS") %>%
  full_join(incident_details_2011, by = "SEQNOS") %>%
  full_join(material_involved_2011, by = "SEQNOS")

full_2012 <- calls_2012 %>%
  full_join(incident_commons_2012, by = "SEQNOS") %>%
  full_join(incident_details_2012, by = "SEQNOS") %>%
  full_join(material_involved_2012, by = "SEQNOS")

full_2013 <- calls_2013 %>%
  full_join(incident_commons_2013, by = "SEQNOS") %>%
  full_join(incident_details_2013, by = "SEQNOS") %>%
  full_join(material_involved_2013, by = "SEQNOS")

full_2014 <- calls_2014 %>%
  full_join(incident_commons_2014, by = "SEQNOS") %>%
  full_join(incident_details_2014, by = "SEQNOS") %>%
  full_join(material_involved_2014, by = "SEQNOS")

full_2015 <- calls_2015 %>%
  full_join(incident_commons_2015, by = "SEQNOS") %>%
  full_join(incident_details_2015, by = "SEQNOS") %>%
  full_join(material_involved_2015, by = "SEQNOS")

full_2016 <- calls_2016 %>%
  full_join(incident_commons_2016, by = "SEQNOS") %>%
  full_join(incident_details_2016, by = "SEQNOS") %>%
  full_join(material_involved_2016, by = "SEQNOS")

full_2017 <- calls_2017 %>%
  full_join(incident_commons_2017, by = "SEQNOS") %>%
  full_join(incident_details_2017, by = "SEQNOS") %>%
  full_join(material_involved_2017, by = "SEQNOS")

full_2017 <- calls_2017 %>%
  full_join(incident_commons_2017, by = "SEQNOS") %>%
  full_join(incident_details_2017, by = "SEQNOS") %>%
  full_join(material_involved_2017, by = "SEQNOS")

full_2018 <- calls_2018 %>%
  full_join(incident_commons_2018, by = "SEQNOS") %>%
  full_join(incident_details_2018, by = "SEQNOS") %>%
  full_join(material_involved_2018, by = "SEQNOS")

full_2019 <- calls_2019 %>%
  full_join(incident_commons_2019, by = "SEQNOS") %>%
  full_join(incident_details_2019, by = "SEQNOS") %>%
  full_join(material_involved_2019, by = "SEQNOS")

full_2020 <- calls_2020 %>%
  full_join(incident_commons_2020, by = "SEQNOS") %>%
  full_join(incident_details_2020, by = "SEQNOS") %>%
  full_join(material_involved_2020, by = "SEQNOS")

full_2021 <- calls_2021 %>%
  full_join(incident_commons_2021, by = "SEQNOS") %>%
  full_join(incident_details_2021, by = "SEQNOS") %>%
  full_join(material_involved_2021, by = "SEQNOS")

full_2022 <- calls_2022 %>%
  full_join(incident_commons_2022, by = "SEQNOS") %>%
  full_join(incident_details_2022, by = "SEQNOS") %>%
  full_join(material_involved_2022, by = "SEQNOS")

full_2023 <- calls_2023 %>%
  full_join(incident_commons_2023, by = "SEQNOS") %>%
  full_join(incident_details_2023, by = "SEQNOS") %>%
  full_join(material_involved_2023, by = "SEQNOS")

full_2024 <- calls_2024 %>%
  full_join(incident_commons_2024, by = "SEQNOS") %>%
  full_join(incident_details_2024, by = "SEQNOS") %>%
  full_join(material_involved_2024, by = "SEQNOS")
```

```{r}
# Export the data frame to a CSV file
write.csv(full_2010, "~/Oil-Refinery/Analysis/Join Data/full_2010.csv", row.names = FALSE)
write.csv(full_2011, "~/Oil-Refinery/Analysis/Join Data/full_2011.csv", row.names = FALSE)
write.csv(full_2012, "~/Oil-Refinery/Analysis/Join Data/full_2012.csv", row.names = FALSE)
write.csv(full_2013, "~/Oil-Refinery/Analysis/Join Data/full_2013.csv", row.names = FALSE)
write.csv(full_2014, "~/Oil-Refinery/Analysis/Join Data/full_2014.csv", row.names = FALSE)
write.csv(full_2015, "~/Oil-Refinery/Analysis/Join Data/full_2015.csv", row.names = FALSE)
write.csv(full_2016, "~/Oil-Refinery/Analysis/Join Data/full_2016.csv", row.names = FALSE)
write.csv(full_2017, "~/Oil-Refinery/Analysis/Join Data/full_2017.csv", row.names = FALSE)
write.csv(full_2018, "~/Oil-Refinery/Analysis/Join Data/full_2018.csv", row.names = FALSE)
write.csv(full_2019, "~/Oil-Refinery/Analysis/Join Data/full_2019.csv", row.names = FALSE)
write.csv(full_2020, "~/Oil-Refinery/Analysis/Join Data/full_2020.csv", row.names = FALSE)
write.csv(full_2021, "~/Oil-Refinery/Analysis/Join Data/full_2021.csv", row.names = FALSE)
write.csv(full_2022, "~/Oil-Refinery/Analysis/Join Data/full_2022.csv", row.names = FALSE)
write.csv(full_2023, "~/Oil-Refinery/Analysis/Join Data/full_2023.csv", row.names = FALSE)
write.csv(full_2024, "~/Oil-Refinery/Analysis/Join Data/full_2024.csv", row.names = FALSE)
```

```{r}
full_2010$RESPONSIBLE_ZIP <- as.double(full_2010$RESPONSIBLE_ZIP)
full_2011$RESPONSIBLE_ZIP <- as.double(full_2011$RESPONSIBLE_ZIP)
full_2012$RESPONSIBLE_ZIP <- as.double(full_2012$RESPONSIBLE_ZIP)
full_2013$RESPONSIBLE_ZIP <- as.double(full_2013$RESPONSIBLE_ZIP)
full_2014$RESPONSIBLE_ZIP <- as.double(full_2014$RESPONSIBLE_ZIP)
full_2015$RESPONSIBLE_ZIP <- as.double(full_2015$RESPONSIBLE_ZIP)
full_2016$RESPONSIBLE_ZIP <- as.double(full_2016$RESPONSIBLE_ZIP)
full_2017$RESPONSIBLE_ZIP <- as.double(full_2017$RESPONSIBLE_ZIP)
full_2018$RESPONSIBLE_ZIP <- as.double(full_2018$RESPONSIBLE_ZIP)
full_2019$RESPONSIBLE_ZIP <- as.double(full_2019$RESPONSIBLE_ZIP)
full_2020$RESPONSIBLE_ZIP <- as.double(full_2020$RESPONSIBLE_ZIP)
full_2021$RESPONSIBLE_ZIP <- as.double(full_2021$RESPONSIBLE_ZIP)
full_2022$RESPONSIBLE_ZIP <- as.double(full_2022$RESPONSIBLE_ZIP)
full_2023$RESPONSIBLE_ZIP <- as.double(full_2023$RESPONSIBLE_ZIP)
full_2024$RESPONSIBLE_ZIP <- as.double(full_2024$RESPONSIBLE_ZIP)
```


```{r}
# List all data frame names
data_frames <- mget(ls(pattern = "^full_\\d{4}$"))

# Extract column names from each data frame
col_names_list <- lapply(data_frames, names)

# Find unique column names across all data frames
unique_col_names <- unique(unlist(col_names_list))

# Print unique column names
print(unique_col_names)

```
```{r}
# Identify columns in each data frame
column_diffs <- lapply(data_frames, function(df) setdiff(unique_col_names, names(df)))

# Print columns that are not in each data frame
print(column_diffs)

```

```{r}
# Get columns in the 2023 dataset
columns_2023 <- colnames(full_2023)

# Get columns in the reference dataset
columns_reference <- colnames(full_2010)  # assuming full_2010 has the correct columns

# Find extra columns in the 2023 dataset
extra_columns <- setdiff(columns_2023, columns_reference)
missing_columns <- setdiff(columns_reference, columns_2023)

# Print extra columns
print(extra_columns)

# Print missing columns
print(missing_columns)
```

```{r}
# Keep only the columns present in the reference data set
full_2023 <- full_2023[, columns_reference]
```

```{r}
convert_columns <- function(df, template) {
  for (col in intersect(names(df), names(template))) {
    template_class <- class(template[[col]])
    
    if ("character" %in% template_class) {
      df[[col]] <- as.character(df[[col]])
    } else if ("numeric" %in% template_class || "double" %in% template_class) {
      df[[col]] <- as.numeric(df[[col]])
    } else if ("integer" %in% template_class) {
      df[[col]] <- as.integer(df[[col]])
    } else if ("factor" %in% template_class) {
      df[[col]] <- as.factor(df[[col]])
    } else if ("Date" %in% template_class) {
      df[[col]] <- as.Date(df[[col]])
    } else if ("POSIXct" %in% template_class) {
      df[[col]] <- as.POSIXct(df[[col]], format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
    } else if ("logical" %in% template_class) {
      df[[col]] <- as.logical(df[[col]])
    } else if ("character" %in% template_class & "logical" %in% class(df[[col]])) {
      df[[col]] <- as.character(df[[col]])
    }
  }
  return(df)
}

```

```{r}
# Apply the conversion to all data frames to match full_2017
full_2010 <- convert_columns(full_2010, full_2010)
full_2011 <- convert_columns(full_2011, full_2010)
full_2012 <- convert_columns(full_2012, full_2010)
full_2013 <- convert_columns(full_2013, full_2010)
full_2014 <- convert_columns(full_2014, full_2010)
full_2015 <- convert_columns(full_2015, full_2010)
full_2016 <- convert_columns(full_2016, full_2010)
full_2017 <- convert_columns(full_2017, full_2010)
full_2018 <- convert_columns(full_2018, full_2010)
full_2019 <- convert_columns(full_2019, full_2010)
full_2020 <- convert_columns(full_2020, full_2010)
full_2021 <- convert_columns(full_2021, full_2010)
full_2022 <- convert_columns(full_2022, full_2010)
full_2023 <- convert_columns(full_2023, full_2010)
full_2024 <- convert_columns(full_2024, full_2010)
```

```{r}
df_full <- bind_rows(full_2010, full_2011, full_2012, full_2013, full_2014, full_2015, full_2016, full_2017, full_2018, full_2019, full_2020, full_2021, full_2022, full_2023, full_2024)
```

```{r}
#write.csv(df_full, "~/Oil-Refinery/Analysis/Join Data/Full Merge/full_merge.csv", row.names = FALSE)
write.csv(df_full, gzfile("~/Oil-Refinery/Analysis/Join Data/Full Merge/full_merge_compressed.csv.gz"), row.names = FALSE)

```

```{r}
company_list <- read.csv("~/Oil-Refinery/Data/Company_list.csv")
names(company_list)
```

```{r}
company_list$Name <- company_list$Name.in.NRC.Data

company_list <- company_list %>%
  select("Name")
```


```{r}
company_list <- company_list %>%
  filter(!is.na(Name) & trimws(Name) != "" & Name != "-") %>%
  distinct(Name, .keep_all = TRUE) %>%
  separate_rows(Name, sep = ",") %>%
  mutate(Name = trimws(Name))
```


```{r}
# Create a vector of the names or strings you want to match
search_strings <- company_list$Name
```

```{r}
# Filter the large dataset
filtered_data <- df_full %>%
  filter(str_detect(RESPONSIBLE_COMPANY, paste(search_strings, collapse = "|")))
```

```{r}
filtered_data <- filtered_data %>%
  mutate(
    LONG = paste(LONG_DEG, "°", LONG_MIN, "'", LONG_SEC, "''", LONG_QUAD, sep = " "),
    LAT = paste(LAT_DEG, "°", LAT_MIN, "'", LAT_SEC, "''", LAT_QUAD, sep = " ")
  )
```

```{r}
filtered_data_na <- filtered_data %>%
  filter(!is.na(LONG_DEG) & !is.na(LAT_DEG))
```


```{r}
#write.csv(filtered_data, "~/Oil-Refinery/Analysis/Join Data/Filtered/filtered_data.csv", row.names = FALSE)

write.csv(filtered_data_na, "~/Oil-Refinery/Analysis/Join Data/Filtered/filtered_data_no_na.csv", row.names = FALSE)
```


